apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: slacklistener-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: slacklistener
    spec:
      containers:
      - name: slacklistener
        image: docker-registry.connect.cd/slacklistener:latest
        imagePullPolicy: Always
        command:
          - java
          - -Xms128m
          - -Xmx768m
          - -jar
          - /usr/share/slacklistener/app.jar
          - -P/etc/java-config/slack-listener.properties
          - -Dlog4j.configurationFile=/etc/logs-config/log4j2.xml
        resources:
          limits:
            cpu: "0.25"
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 512Mi
        env:
        - name: authToken
          valueFrom:
            secretKeyRef:
              name: slack-auth-token
              key: authtoken
        volumeMounts:
        - mountPath: /etc/java-config
          name: java-config
        - mountPath: /etc/logs-config
          name: logs-config
      volumes:
      - configMap:
          defaultMode: 420
          name: services-config
        name: java-config
      - configMap:
          defaultMode: 420
          name: logs-config
        name: logs-config
      imagePullSecrets:
      - name: regsecret
