apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: slacklistener-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: slacklistener
    spec:
      containers:
      - name: slacklistener
        image: darthshana/slacklistener:0.0.1-SNAPSHOT
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: sample-slack-app-config