apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: slack-sentiment-analyser
  namespace: sample-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: slack-sentiment-analyser
    spec:
      containers:
      - name: slacksentimentanalyser
        image: slacksentimentanalyser:latest
        imagePullPolicy: IfNotPresent
        command:
          - java
          - -Xms128m
          - -Xmx768m
          - -jar
          - /usr/share/slacksentimentanalyser/app.jar
          - -P/etc/java-config/slack-sentiment-analyser.properties
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/java-config
          name: java-config
      volumes:
      - configMap:
          defaultMode: 420
          name: sample-app-config
        name: java-config

