apiVersion: v1
kind: Service
metadata:
  name: slack-sentiment-analyser
  namespace: sample-app
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: slack-sentiment-analyser
  type: LoadBalancer
